### ISSUE TITLE
No Python3 support

### ISSUE THREAD

**Issue by zeusttu** [justinvh/Markdown-LaTeX#20]
Code only works in Python2. I need it to run in Python3 for a Gedit plugin.

**Comment by T-800** [comment]
My Python 3 version of this extension.

https://github.com/T-800/Markdown-latex-python3

**Comment by zeusttu** [comment]
I've been working on it myself too, but in a way that tries to be compatible with both Python2 and Python3. I've also fixed some other things like putting temporary files in /tmp instead of the working directory, so I think I'm sticking with my code which is almost ready for a merge. Though I also took a look at your code which seems to use svg instead of png, I like that, maybe I'm gonna do that too!

**Comment by zeratax** [comment]
I guess this can be closed now, since #21 has been merged?

**Comment by zeusttu** [comment]
To be honest this is so long ago that I barely remember working with this. As a result I'm not really in the position to tell whether it's really fixed at this point, but you're probably right that it is. I'll just close this issue, if anyone still has problems with this they can chime in and we can reopen it.

Thanks for reminding me that I sometime created this!
