### ISSUE TITLE
escape percentage sign?

### ISSUE THREAD

**Issue by 404pnf** [justinvh/Markdown-LaTeX#8]
consider the following text:

      from 40% to nearly 80%.  I am accidently entered tex mode.

      from 40\% to nearly 80\%.  I am accidently entered tex mode.

render it with markdown_py -x latex sample.md > sample.html gets:

      <p>from 40<img class='latex-inline math-false' alt='tonearly80' id='tonearly80' src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFYAAAAQBAMAAAB+eZW1AAAAMFBMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAdrsQie9mqyJEMplU3c0GZ1kGAAABc0lEQVQoz43SP0gCURwH8K93cv/UuPCoQQqjCIKgGyJo8gIhiQYhcipQEGsxhBoaGk4IIhelvbqmtpIKIVya2kqhkNpqbsgwspbo906NGix/y/3uvQ/H9/3eAW0rg45Lef5uY5oOLU6N2g4ftxrB5P2CIacAfzubbTUcsOqxMIfx8L+2K4+HgI4Kll5D6InrtLR7F0vBGVOlxCyuRqbJJt+kRQtwf25a+zpuIYfhupDKZOUFDGMUBc7wWO77I7JKFV724dILSsATs3SIAVqRajij3Wt3TjToyTJUEKUNfmYsX9IbNgmcMFtF0RFJ+JDuN5SwbVdkk+XVhY9mBqXvhyXjHHQZStm2gTSLcAhoWRMRsgJlGGpapQYpoIuhTMOKG8xuAZc0s3fw1UkxKt2wiyKLNUxkde58u5FBsQfKmTgV8jJdRK+KoI/NbKeenledU6qjsPy4V8/JY+uAwSwf1Ex023P9o+yjdVZFR+e/2oH31+sXpx1gwC/5fcgAAAAASUVORK5CYII='>.  I am accidently entered tex mode.</p>
      <p>from 40\% to nearly 80\%.  I am accidently entered tex mode.</p>          

What's the proper way to escape the % sign?

**Comment by tommy0521** [comment]
you can use **{% raw %}** from 40% to nearly 80%.  I am accidently entered tex mode. **{% endraw %}**

**Comment by 404pnf** [comment]
Thank you!
